server {
    listen 172.17.0.1:8080;
    server_name madarorbit.com www.madarorbit.com;

    root /var/www/madarorbit;
    index index.html;

    access_log /var/log/nginx/madarorbit.access.log;
    error_log /var/log/nginx/madarorbit.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|webp|svg|ico|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}
